version: "3"

services:
  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./sites:/sites
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: php:7.4-fpm
    container_name: php-fpm
    volumes:
      - ./sites:/sites
